name: C/C++ CI

on:
  push:
    branches: [ test_action ]
  pull_request:
    branches: [ test_action ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: create buil folder
      run: mkdir build
    - name: go to folder
      run: cd build
    - name: configure
      run: ls
    - name: make
      run: make
    - name: test
      run: ./tests/EngineSFML_tst
    
